language: node_js
node_js:
  - stable
script:
  - npm test
  - npm run coverage
before_install:
    npm install react react-dom
after_script:
    npm install coveralls && cat ./coverage/lcov.info | coveralls